/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FriendVisit {
  'message' : string,
  'visitor' : Principal,
  'timestamp' : Time,
}
export interface PastelSkyProfile {
  'lastActiveTime' : Time,
  'rewards' : Array<QudoReward>,
  'world' : SkyWorldState,
  'visits' : Array<FriendVisit>,
}
export interface PersistentStar {
  'x' : number,
  'y' : number,
  'brightness' : number,
}
export interface QudoReward {
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface SkyWorldState {
  'theme' : string,
  'lastVisitedTime' : [] | [Time],
  'persistentStars' : Array<PersistentStar>,
  'totalFlowersCollected' : bigint,
  'highScore' : bigint,
  'totalSparklesCollected' : bigint,
  'activeSessions' : bigint,
  'friends' : Array<Principal>,
  'lastQudoBoostTime' : Time,
  'decorations' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'pastelSkyProfile' : [] | [PastelSkyProfile],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriend' : ActorMethod<[Principal], undefined>,
  'adminGetUserProfile' : ActorMethod<[Principal], [] | [PastelSkyProfile]>,
  'adminRemoveReward' : ActorMethod<[Principal, bigint], undefined>,
  'adminResetUserWorld' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendSkyWorld' : ActorMethod<[Principal], [] | [SkyWorldState]>,
  'getHighScores' : ActorMethod<[], Array<PastelSkyProfile>>,
  'getMyVisits' : ActorMethod<[], Array<FriendVisit>>,
  'getRewards' : ActorMethod<[], Array<QudoReward>>,
  'getSkyWorld' : ActorMethod<[], [] | [PastelSkyProfile]>,
  'getStarsByBrightness' : ActorMethod<[], Array<PersistentStar>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSkyWorld' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'recordReward' : ActorMethod<[QudoReward], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSkyWorld' : ActorMethod<[SkyWorldState], undefined>,
  'visitFriend' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];