/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const QudoReward = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const PersistentStar = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'brightness' : IDL.Float64,
});
export const SkyWorldState = IDL.Record({
  'theme' : IDL.Text,
  'lastVisitedTime' : IDL.Opt(Time),
  'persistentStars' : IDL.Vec(PersistentStar),
  'totalFlowersCollected' : IDL.Nat,
  'highScore' : IDL.Nat,
  'totalSparklesCollected' : IDL.Nat,
  'activeSessions' : IDL.Nat,
  'friends' : IDL.Vec(IDL.Principal),
  'lastQudoBoostTime' : Time,
  'decorations' : IDL.Vec(IDL.Text),
});
export const FriendVisit = IDL.Record({
  'message' : IDL.Text,
  'visitor' : IDL.Principal,
  'timestamp' : Time,
});
export const PastelSkyProfile = IDL.Record({
  'lastActiveTime' : Time,
  'rewards' : IDL.Vec(QudoReward),
  'world' : SkyWorldState,
  'visits' : IDL.Vec(FriendVisit),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'pastelSkyProfile' : IDL.Opt(PastelSkyProfile),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'adminGetUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PastelSkyProfile)],
      ['query'],
    ),
  'adminRemoveReward' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminResetUserWorld' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFriendSkyWorld' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SkyWorldState)],
      ['query'],
    ),
  'getHighScores' : IDL.Func([], [IDL.Vec(PastelSkyProfile)], ['query']),
  'getMyVisits' : IDL.Func([], [IDL.Vec(FriendVisit)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(QudoReward)], ['query']),
  'getSkyWorld' : IDL.Func([], [IDL.Opt(PastelSkyProfile)], ['query']),
  'getStarsByBrightness' : IDL.Func([], [IDL.Vec(PersistentStar)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSkyWorld' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'recordReward' : IDL.Func([QudoReward], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSkyWorld' : IDL.Func([SkyWorldState], [], []),
  'visitFriend' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const QudoReward = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const PersistentStar = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'brightness' : IDL.Float64,
  });
  const SkyWorldState = IDL.Record({
    'theme' : IDL.Text,
    'lastVisitedTime' : IDL.Opt(Time),
    'persistentStars' : IDL.Vec(PersistentStar),
    'totalFlowersCollected' : IDL.Nat,
    'highScore' : IDL.Nat,
    'totalSparklesCollected' : IDL.Nat,
    'activeSessions' : IDL.Nat,
    'friends' : IDL.Vec(IDL.Principal),
    'lastQudoBoostTime' : Time,
    'decorations' : IDL.Vec(IDL.Text),
  });
  const FriendVisit = IDL.Record({
    'message' : IDL.Text,
    'visitor' : IDL.Principal,
    'timestamp' : Time,
  });
  const PastelSkyProfile = IDL.Record({
    'lastActiveTime' : Time,
    'rewards' : IDL.Vec(QudoReward),
    'world' : SkyWorldState,
    'visits' : IDL.Vec(FriendVisit),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'pastelSkyProfile' : IDL.Opt(PastelSkyProfile),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'adminGetUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PastelSkyProfile)],
        ['query'],
      ),
    'adminRemoveReward' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminResetUserWorld' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFriendSkyWorld' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SkyWorldState)],
        ['query'],
      ),
    'getHighScores' : IDL.Func([], [IDL.Vec(PastelSkyProfile)], ['query']),
    'getMyVisits' : IDL.Func([], [IDL.Vec(FriendVisit)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(QudoReward)], ['query']),
    'getSkyWorld' : IDL.Func([], [IDL.Opt(PastelSkyProfile)], ['query']),
    'getStarsByBrightness' : IDL.Func([], [IDL.Vec(PersistentStar)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSkyWorld' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'recordReward' : IDL.Func([QudoReward], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSkyWorld' : IDL.Func([SkyWorldState], [], []),
    'visitFriend' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };