/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface QudoReward {
    description: string;
    timestamp: Time;
    amount: bigint;
}
export interface PersistentStar {
    x: number;
    y: number;
    brightness: number;
}
export interface PastelSkyProfile {
    lastActiveTime: Time;
    rewards: Array<QudoReward>;
    world: SkyWorldState;
    visits: Array<FriendVisit>;
}
export interface SkyWorldState {
    theme: string;
    lastVisitedTime?: Time;
    persistentStars: Array<PersistentStar>;
    totalFlowersCollected: bigint;
    highScore: bigint;
    totalSparklesCollected: bigint;
    activeSessions: bigint;
    friends: Array<Principal>;
    lastQudoBoostTime: Time;
    decorations: Array<string>;
}
export interface UserProfile {
    pastelSkyProfile?: PastelSkyProfile;
    name: string;
}
export interface FriendVisit {
    message: string;
    visitor: Principal;
    timestamp: Time;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFriend(friend: Principal): Promise<void>;
    adminGetUserProfile(user: Principal): Promise<PastelSkyProfile | null>;
    adminRemoveReward(user: Principal, rewardIndex: bigint): Promise<void>;
    adminResetUserWorld(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFriendSkyWorld(friend: Principal): Promise<SkyWorldState | null>;
    getHighScores(): Promise<Array<PastelSkyProfile>>;
    getMyVisits(): Promise<Array<FriendVisit>>;
    getRewards(): Promise<Array<QudoReward>>;
    getSkyWorld(): Promise<PastelSkyProfile | null>;
    getStarsByBrightness(): Promise<Array<PersistentStar>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeSkyWorld(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isRegistered(): Promise<boolean>;
    recordReward(reward: QudoReward): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSkyWorld(world: SkyWorldState): Promise<void>;
    visitFriend(friend: Principal, message: string): Promise<void>;
}
import type { FriendVisit as _FriendVisit, PastelSkyProfile as _PastelSkyProfile, PersistentStar as _PersistentStar, QudoReward as _QudoReward, SkyWorldState as _SkyWorldState, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFriend(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFriend(arg0);
            return result;
        }
    }
    async adminGetUserProfile(arg0: Principal): Promise<PastelSkyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserProfile(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserProfile(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRemoveReward(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveReward(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveReward(arg0, arg1);
            return result;
        }
    }
    async adminResetUserWorld(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetUserWorld(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetUserWorld(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendSkyWorld(arg0: Principal): Promise<SkyWorldState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendSkyWorld(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendSkyWorld(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHighScores(): Promise<Array<PastelSkyProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHighScores();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHighScores();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVisits(): Promise<Array<FriendVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVisits();
            return result;
        }
    }
    async getRewards(): Promise<Array<QudoReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getSkyWorld(): Promise<PastelSkyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkyWorld();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkyWorld();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStarsByBrightness(): Promise<Array<PersistentStar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStarsByBrightness();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStarsByBrightness();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSkyWorld(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSkyWorld();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSkyWorld();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async recordReward(arg0: QudoReward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordReward(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSkyWorld(arg0: SkyWorldState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkyWorld(to_candid_SkyWorldState_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkyWorld(to_candid_SkyWorldState_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async visitFriend(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.visitFriend(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visitFriend(arg0, arg1);
            return result;
        }
    }
}
function from_candid_PastelSkyProfile_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PastelSkyProfile): PastelSkyProfile {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SkyWorldState_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkyWorldState): SkyWorldState {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PastelSkyProfile]): PastelSkyProfile | null {
    return value.length === 0 ? null : from_candid_PastelSkyProfile_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkyWorldState]): SkyWorldState | null {
    return value.length === 0 ? null : from_candid_SkyWorldState_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pastelSkyProfile: [] | [_PastelSkyProfile];
    name: string;
}): {
    pastelSkyProfile?: PastelSkyProfile;
    name: string;
} {
    return {
        pastelSkyProfile: record_opt_to_undefined(from_candid_opt_n1(_uploadFile, _downloadFile, value.pastelSkyProfile)),
        name: value.name
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastActiveTime: _Time;
    rewards: Array<_QudoReward>;
    world: _SkyWorldState;
    visits: Array<_FriendVisit>;
}): {
    lastActiveTime: Time;
    rewards: Array<QudoReward>;
    world: SkyWorldState;
    visits: Array<FriendVisit>;
} {
    return {
        lastActiveTime: value.lastActiveTime,
        rewards: value.rewards,
        world: from_candid_SkyWorldState_n4(_uploadFile, _downloadFile, value.world),
        visits: value.visits
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    lastVisitedTime: [] | [_Time];
    persistentStars: Array<_PersistentStar>;
    totalFlowersCollected: bigint;
    highScore: bigint;
    totalSparklesCollected: bigint;
    activeSessions: bigint;
    friends: Array<Principal>;
    lastQudoBoostTime: _Time;
    decorations: Array<string>;
}): {
    theme: string;
    lastVisitedTime?: Time;
    persistentStars: Array<PersistentStar>;
    totalFlowersCollected: bigint;
    highScore: bigint;
    totalSparklesCollected: bigint;
    activeSessions: bigint;
    friends: Array<Principal>;
    lastQudoBoostTime: Time;
    decorations: Array<string>;
} {
    return {
        theme: value.theme,
        lastVisitedTime: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastVisitedTime)),
        persistentStars: value.persistentStars,
        totalFlowersCollected: value.totalFlowersCollected,
        highScore: value.highScore,
        totalSparklesCollected: value.totalSparklesCollected,
        activeSessions: value.activeSessions,
        friends: value.friends,
        lastQudoBoostTime: value.lastQudoBoostTime,
        decorations: value.decorations
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PastelSkyProfile>): Array<PastelSkyProfile> {
    return value.map((x)=>from_candid_PastelSkyProfile_n2(_uploadFile, _downloadFile, x));
}
function to_candid_PastelSkyProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PastelSkyProfile): _PastelSkyProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_SkyWorldState_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkyWorldState): _SkyWorldState {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pastelSkyProfile?: PastelSkyProfile;
    name: string;
}): {
    pastelSkyProfile: [] | [_PastelSkyProfile];
    name: string;
} {
    return {
        pastelSkyProfile: value.pastelSkyProfile ? candid_some(to_candid_PastelSkyProfile_n18(_uploadFile, _downloadFile, value.pastelSkyProfile)) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastActiveTime: Time;
    rewards: Array<QudoReward>;
    world: SkyWorldState;
    visits: Array<FriendVisit>;
}): {
    lastActiveTime: _Time;
    rewards: Array<_QudoReward>;
    world: _SkyWorldState;
    visits: Array<_FriendVisit>;
} {
    return {
        lastActiveTime: value.lastActiveTime,
        rewards: value.rewards,
        world: to_candid_SkyWorldState_n20(_uploadFile, _downloadFile, value.world),
        visits: value.visits
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    lastVisitedTime?: Time;
    persistentStars: Array<PersistentStar>;
    totalFlowersCollected: bigint;
    highScore: bigint;
    totalSparklesCollected: bigint;
    activeSessions: bigint;
    friends: Array<Principal>;
    lastQudoBoostTime: Time;
    decorations: Array<string>;
}): {
    theme: string;
    lastVisitedTime: [] | [_Time];
    persistentStars: Array<_PersistentStar>;
    totalFlowersCollected: bigint;
    highScore: bigint;
    totalSparklesCollected: bigint;
    activeSessions: bigint;
    friends: Array<Principal>;
    lastQudoBoostTime: _Time;
    decorations: Array<string>;
} {
    return {
        theme: value.theme,
        lastVisitedTime: value.lastVisitedTime ? candid_some(value.lastVisitedTime) : candid_none(),
        persistentStars: value.persistentStars,
        totalFlowersCollected: value.totalFlowersCollected,
        highScore: value.highScore,
        totalSparklesCollected: value.totalSparklesCollected,
        activeSessions: value.activeSessions,
        friends: value.friends,
        lastQudoBoostTime: value.lastQudoBoostTime,
        decorations: value.decorations
    };
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
